# Generated by Django 6.0.2 on 2026-04-19 13:11

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_projectmodel_slug_and_more'),
        ('team', '0009_alter_teammembermodel_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Dono do Projeto'), ('MANAGER', 'Gerente de Time'), ('MEMBER', 'Desenvolvedor'), ('GUEST', 'Convidado')], default='MEMBER', max_length=20)),
                ('link', models.CharField(blank=True, editable=False, null=True, unique=True)),
                ('expiration_date', models.DateField(default=datetime.datetime(2026, 4, 20, 13, 11, 27, 95592, tzinfo=datetime.timezone.utc), editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('DECLINED', 'Recusado'), ('EXPIRED', 'Expirado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_made', to=settings.AUTH_USER_MODEL)),
                ('made_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectmodel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teammodel')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
    ]
