# Generated by Django 6.0.2 on 2026-04-19 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 13, 23, 3, 414995, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='invitationmodel',
            name='made_for',
            field=models.EmailField(max_length=254),
        ),
    ]
