# Generated by Django 6.0.2 on 2026-04-19 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_invitationmodel_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 13, 44, 35, 525984, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
