# Generated by Django 6.0.2 on 2026-04-19 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_alter_invitationmodel_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationmodel',
            name='role',
        ),
        migrations.AlterField(
            model_name='invitationmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 13, 46, 13, 171245, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
