# Generated by Django 6.0.2 on 2026-04-19 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_remove_invitationmodel_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 20, 14, 4, 36, 731537, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
