# Generated by Django 6.0.2 on 2026-04-29 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_alter_invitationmodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2026, 4, 30), editable=False),
        ),
    ]
