# Generated by Django 6.0.2 on 2026-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_alter_invitationmodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmodel',
            name='expiration_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
