# Generated by Django 6.0.2 on 2026-05-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_alter_invitationmodel_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationmodel',
            name='answered',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
