# Generated by Django 6.0.2 on 2026-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_invitationmodel_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationmodel',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
