# Generated by Django 6.0.2 on 2026-03-30 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('team', '0007_teammembermodel_permission_related_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='projectmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='unique_slug_active_project'),
        ),
    ]
