# Generated by Django 6.0.2 on 2026-06-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectmodel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='deleted_at',
        ),
    ]
