# Generated by Django 6.0.2 on 2026-03-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammembermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='members',
        ),
    ]
