# Generated by Django 6.0.2 on 2026-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_teammodel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembermodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
