# Generated by Django 6.0.2 on 2026-03-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teammembermodel_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembermodel',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Dono do Projeto'), ('MANAGER', 'Gerente de Time'), ('MEMBER', 'Desenvolvedor'), ('GUEST', 'Convidado')], default='MEMBER', max_length=20),
        ),
    ]
