# Generated by Django 6.0.2 on 2026-03-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_teammembermodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembermodel',
            name='deleted_at',
        ),
    ]
