# Generated by Django 6.0.2 on 2026-03-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_teammembermodel_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembermodel',
            name='permission_related_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammembermodel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='team.teammodel'),
        ),
    ]
