# Generated by Django 6.0.2 on 2026-04-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_teammembermodel_permission_related_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembermodel',
            name='permission_related_project',
            field=models.BooleanField(default=False),
        ),
    ]
