# Generated by Django 6.0.2 on 2026-04-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_teammembermodel_permission_related_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembermodel',
            unique_together=set(),
        ),
    ]
