# Generated by Django 6.0.2 on 2026-06-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_teammembermodel_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='deleted_at',
        ),
    ]
