# Generated by Django 6.0.2 on 2026-03-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner (Dono do Projeto)'), ('TEAM_MANAGER', 'Team Manager (Gerente)'), ('MEMBER', 'Member (Desenvolvedor)'), ('GUEST', 'Guest (Stakeholder)')], default='MEMBER'),
        ),
    ]
