# Generated by Django 6.0.2 on 2026-03-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
