# Generated by Django 6.0.2 on 2026-06-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='deleted_at',
        ),
    ]
