# Generated by Django 6.0.2 on 2026-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
        ('team', '0003_remove_teammodel_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintmodel',
            name='team',
        ),
        migrations.AddField(
            model_name='sprintmodel',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='sprints', to='team.teammodel'),
        ),
    ]
