# Generated by Django 6.0.2 on 2026-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_remove_sprintmodel_team_sprintmodel_teams'),
        ('team', '0003_remove_teammodel_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmodel',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='sprints', to='team.teammodel'),
        ),
    ]
