# Generated by Django 6.0.2 on 2026-03-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_alter_sprintmodel_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintmodel',
            name='progress',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
