# Generated by Django 6.0.2 on 2026-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0004_sprintmodel_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmodel',
            name='progress',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
    ]
