# Generated by Django 6.0.2 on 2026-06-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0006_alter_sprintmodel_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintmodel',
            name='deleted_at',
        ),
    ]
